version: "3"
services:
  db:
    image: mongo:5-focal
    restart: always
    networks:
      - private
    environment:
      - MONGO_INITDB_USERNAME=personal_site
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}

  site:
    build: ./src/site/
    restart: always
    networks:
      - private
      - public
    depends_on:
      - db
    ports:
      - "80:3000"
networks:
  private:
  public:
